from database.models import Stock, Session
import asyncio
nyse_stocks = [
    ("A", "Agilent Technologies, Inc."),
    ("AA", "Alcoa Corporation"),
    ("AADX", "Applied Aerospace & Defense, Inc."),
    ("AAMI", "Acadian Asset Management Inc."),
    ("AAUC", "Allied Gold Corporation"),
    ("ABBV", "AbbVie Inc."),
    ("ABCB", "Ameris Bancorp"),
    ("ABG", "Asbury Automotive Group Inc"),
    ("ABM", "ABM Industries Incorporated"),
    ("ABT", "Abbott Laboratories"),
    ("ABX", "Abacus Global Management, Inc. Class A"),
    ("ACA", "Arcosa, Inc."),
    ("ACCO", "Acco Brands Corporation"),
    ("ACH", "Accendra Health, Inc."),
    ("ACHR", "Archer Aviation Inc. Class A"),
    ("ACI", "Albertsons Companies, Inc. Class A"),
    ("ACM", "AECOM"),
    ("ACN", "Accenture plc Class A"),
    ("ACR", "ACRES Commercial Realty Corp."),
    ("ACRE", "Ares Commercial Real Estate Corporation"),
    ("ACVA", "ACV Auctions Inc. Class A"),
    ("AD", "Array Digital Infrastructure, Inc."),
    ("ADC", "Agree Realty Corporation"),
    ("ADCT", "ADC Therapeutics SA"),
    ("ADIG", "ADI Global Distribution Inc."),
    ("ADNT", "Adient plc"),
    ("ADT", "ADT Inc."),
    ("AEE", "Ameren Corporation"),
    ("AEM", "Agnico Eagle Mines Limited"),
    ("AEO", "American Eagle Outfitters, Inc."),
    ("AER", "AerCap Holdings N.V."),
    ("AES", "The AES Corporation"),
    ("AESI", "Atlas Energy Solutions Inc."),
    ("AEXA", "American Exceptionalism Acquisition Corp. A Class A"),
    ("AFG", "American Financial Group, Inc."),
    ("AFL", "AFLAC Incorporated"),
    ("AG", "First Majestic Silver Corp."),
    ("AGBK", "AGI Inc Class A"),
    ("AGCO", "AGCO Corporation"),
    ("AGI", "Alamos Gold Inc. Class A"),
    ("AGL", "agilon health, inc."),
    ("AGM", "Federal Agricultural Mortgage Corporation"),
    ("AGO", "Assured Guaranty Ltd."),
    ("AGRO", "Adecoagro S.A."),
    ("AGX", "Argan, Inc."),
    ("AHR", "American Healthcare REIT, Inc."),
    ("AI", "C3.ai, Inc. Class A"),
    ("AIG", "American International Group, Inc. New"),
    ("AII", "American Integrity Insurance Group, Inc."),
    ("AIIA", "AI Infrastructure Acquisition Corp. Class A"),
    ("AIN", "Albany International Corporation"),
    ("AIR", "AAR Corp."),
    ("AIT", "Applied Industrial Technologies, Inc."),
    ("AIV", "Apartment Investment and Management Company"),
    ("AIZ", "Assurant, Inc."),
    ("AJG", "Arthur J. Gallagher & Co."),
    ("AKA", "a.k.a. Brands Holding Corp."),
    ("ALB", "Albemarle Corporation"),
    ("ALC", "Alcon Inc."),
    ("ALG", "Alamo Group, Inc."),
    ("ALH", "Alliance Laundry Holdings Inc."),
    ("ALIT", "Alight, Inc. Class A"),
    ("ALK", "Alaska Air Group, Inc."),
    ("ALL", "Allstate Corporation (The)"),
    ("ALLE", "Allegion plc"),
    ("ALLY", "Ally Financial Inc."),
    ("ALSN", "Allison Transmission Holdings, Inc."),
    ("ALTG", "Alta Equipment Group Inc. Class A"),
    ("ALUB", "Alussa Energy Acquisition Corp. II Class A"),
    ("ALV", "Autoliv, Inc."),
    ("ALX", "Alexander's, Inc."),
    ("AM", "Antero Midstream Corporation"),
    ("AMBP", "Ardagh Metal Packaging S.A."),
    ("AMBQ", "Ambiq Micro, Inc."),
    ("AMC", "AMC Entertainment Holdings, Inc. Class A"),
    ("AMCR", "Amcor plc"),
    ("AMG", "Affiliated Managers Group, Inc."),
    ("AMH", "American Homes 4 Rent"),
    ("AMP", "Ameriprise Financial, Inc."),
    ("AMPX", "Amprius Technologies, Inc."),
    ("AMPY", "Amplify Energy Corp."),
    ("AMR", "Alpha Metallurgical Resources, Inc."),
    ("AMRC", "Ameresco, Inc. Class A"),
    ("AMRZ", "Amrize Ltd"),
    ("AMT", "American Tower Corporation (REIT)"),
    ("AMTB", "Amerant Bancorp Inc. Class A"),
    ("AMTM", "Amentum Holdings, Inc."),
    ("AMWL", "American Well Corporation Class A"),
    ("AN", "AutoNation, Inc."),
    ("ANDG", "Andersen Group Inc. Class A"),
    ("ANET", "Arista Networks, Inc."),
    ("ANF", "Abercrombie & Fitch Company"),
    ("ANGX", "Angel Studios, Inc. Class A"),
    ("ANRO", "Alto Neuroscience, Inc."),
    ("ANVS", "Annovis Bio, Inc."),
    ("AOMR", "Angel Oak Mortgage REIT, Inc."),
    ("AON", "Aon plc Class A"),
    ("AORT", "Artivion, Inc."),
    ("AOS", "A.O. Smith Corporation"),
    ("APAM", "Artisan Partners Asset Management Inc. Class A"),
    ("APD", "Air Products and Chemicals, Inc."),
    ("APG", "APi Group Corporation"),
    ("APH", "Amphenol Corporation"),
    ("APLE", "Apple Hospitality REIT, Inc."),
    ("APO", "Apollo Global Management, Inc. (New)"),
    ("APTV", "Aptiv PLC"),
    ("AQN", "Algonquin Power & Utilities Corp."),
    ("AR", "Antero Resources Corporation"),
    ("ARCO", "Arcos Dorados Holdings Inc. Class A Shares"),
    ("ARDT", "Ardent Health, Inc."),
    ("ARE", "Alexandria Real Estate Equities, Inc."),
    ("ARES", "Ares Management Corporation Class A"),
    ("ARIS", "Aris Mining Corporation"),
    ("ARL", "American Realty Investors, Inc."),
    ("ARLO", "Arlo Technologies, Inc."),
    ("ARMK", "Aramark"),
    ("AROC", "Archrock, Inc."),
    ("ARW", "Arrow Electronics, Inc."),
    ("ARX", "Accelerant Holdings Class A"),
    ("AS", "Amer Sports, Inc."),
    ("ASAN", "Asana, Inc. Class A"),
    ("ASC", "Ardmore Shipping Corporation"),
    ("ASH", "Ashland Inc."),
    ("ASIC", "Ategrity Specialty Insurance Company Holdings"),
    ("ASIX", "AdvanSix Inc."),
    ("ASPN", "Aspen Aerogels, Inc."),
    ("ASR", "Grupo Aeroportuario del Sureste, S.A. de C.V."),
    ("ATEN", "A10 Networks, Inc."),
    ("ATI", "ATI Inc."),
    ("ATKR", "Atkore Inc."),
    ("ATMU", "Atmus Filtration Technologies Inc."),
    ("ATO", "Atmos Energy Corporation"),
    ("ATR", "AptarGroup, Inc."),
    ("ATS", "ATS Corporation"),
    ("AU", "AngloGold Ashanti PLC"),
    ("AUB", "Atlantic Union Bankshares Corporation"),
    ("AUNA", "Auna SA Class A"),
    ("AVA", "Avista Corporation"),
    ("AVB", "AvalonBay Communities, Inc."),
    ("AVBC", "Avidia Bancorp, Inc."),
    ("AVD", "American Vanguard Corporation"),
    ("AVEX", "AEVEX Corp. Class A"),
    ("AVNT", "Avient Corporation"),
    ("AVTR", "Avantor, Inc."),
    ("AVY", "Avery Dennison Corporation"),
    ("AWI", "Armstrong World Industries Inc"),
    ("AWK", "American Water Works Company, Inc."),
    ("AWR", "American States Water Company"),
    ("AX", "Axos Financial, Inc."),
    ("AXP", "American Express Company"),
    ("AXR", "AMREP Corporation"),
    ("AXS", "Axis Capital Holdings Limited"),
    ("AXTA", "Axalta Coating Systems Ltd."),
    ("AYI", "Acuity Inc."),
    ("AZN", "AstraZeneca PLC"),
    ("AZO", "AutoZone, Inc."),
    ("B", "Barrick Mining Corporation"),
    ("BA", "Boeing Company (The)"),
    ("BAC", "Bank of America Corporation"),
    ("BAH", "Booz Allen Hamilton Holding Corporation"),
    ("BALL", "Ball Corporation"),
    ("BALY", "Bally's Corporation"),
    ("BAM", "Brookfield Asset Management Inc Class A Limited Voting Shares"),
    ("BANC", "Banc of California, Inc."),
    ("BAP", "Credicorp Ltd."),
    ("BARK", "BARK, Inc. Class A"),
    ("BAX", "Baxter International Inc."),
    ("BB", "BlackBerry Limited"),
    ("BBAI", "BigBear.ai, Inc."),
    ("BBBY", "Bed Bath & Beyond, Inc."),
    ("BBDC", "Barings BDC, Inc."),
    ("BBT", "Beacon Financial Corporation"),
    ("BBUC", "Brookfield Business Corporation Class A Subordinate Voting Shares"),
    ("BBVA", "Banco Bilbao Vizcaya Argentaria S.A."),
    ("BBY", "Best Buy Co., Inc."),
    ("BC", "Brunswick Corporation"),
    ("BCC", "Boise Cascade, L.L.C."),
    ("BCE", "BCE, Inc."),
    ("BCO", "Brinks Company (The)"),
    ("BCS", "Barclays PLC"),
    ("BCSF", "Bain Capital Specialty Finance, Inc."),
    ("BCSS", "Bain Capital GSS Investment Corp. Class A"),
    ("BCX", "BlackRock Resources"),
    ("BDC", "Belden Inc"),
    ("BDX", "Becton, Dickinson and Company"),
    ("BE", "Bloom Energy Corporation Class A"),
    ("BEBE", "TGE Value Creative Solutions Corp Class A"),
    ("BEN", "Franklin Resources, Inc."),
    ("BEPC", "Brookfield Renewable Corporation Class A"),
    ("BETA", "Beta Technologies, Inc. Class A"),
    ("BFAM", "Bright Horizons Family Solutions Inc."),
    ("BFH", "Bread Financial Holdings, Inc."),
    ("BFLY", "Butterfly Network, Inc. Class A"),
    ("BFS", "Saul Centers, Inc."),
    ("BG", "Bunge Limited"),
    ("BGS", "B&G Foods, Inc."),
    ("BGSF", "BGSF, Inc."),
    ("BGSI", "Boyd Group Services Inc."),
    ("BH", "Biglari Holdings Inc. Class B"),
    ("BHC", "Bausch Health Companies Inc."),
    ("BHE", "Benchmark Electronics, Inc."),
    ("BHR", "Braemar Hotels & Resorts Inc."),
    ("BHVN", "Biohaven Ltd."),
    ("BIII", "Black Spade Acquisition III Co Class A"),
    ("BILL", "BILL Holdings, Inc."),
    ("BIRK", "Birkenstock Holding plc"),
    ("BJ", "BJ's Wholesale Club Holdings, Inc."),
    ("BKD", "Brookdale Senior Living Inc."),
    ("BKE", "Buckle, Inc. (The)"),
    ("BKH", "Black Hills Corporation"),
    ("BKKT", "Bakkt, Inc. Class A"),
    ("BKSY", "BlackSky Technology Inc. Class A"),
    ("BKV", "BKV Corporation"),
    ("BLCO", "Bausch + Lomb Corporation"),
    ("BLDR", "Builders FirstSource, Inc."),
    ("BLK", "BlackRock, Inc."),
    ("BLND", "Blend Labs, Inc. Class A"),
    ("BLSH", "Bullish"),
    ("BLX", "Bladex, Inc. Class E"),
    ("BMA", "Banco Macro S.A."),
    ("BMI", "Badger Meter, Inc."),
    ("BMNR", "BitMine Immersion Technologies, Inc."),
    ("BMO", "Bank Of Montreal"),
    ("BN", "Brookfield Corporation Class A Limited Voting Shares"),
    ("BNED", "Barnes & Noble Education, Inc."),
    ("BNL", "Broadstone Net Lease, Inc."),
    ("BNT", "Brookfield Wealth Solutions Ltd. Class A"),
    ("BNY", "The Bank of New York Mellon Corporation"),
    ("BOBS", "Bob's Discount Furniture, Inc."),
    ("BOC", "Boston Omaha Corporation Class A"),
    ("BOH", "Bank of Hawaii Corporation"),
    ("BOOT", "Boot Barn Holdings, Inc."),
    ("BORR", "Borr Drilling Limited"),
    ("BOW", "Bowhead Specialty Holdings Inc."),
    ("BOX", "Box, Inc. Class A"),
    ("BP", "BP p.l.c."),
    ("BPT", "BP Prudhoe Bay Royalty Trust"),
    ("BR", "Broadridge Financial Solutions, Inc."),
    ("BRC", "Brady Corporation"),
    ("BRK.A", "Berkshire Hathaway Inc. Class A"),
    ("BRK.B", "Berkshire Hathaway Inc. Class B"),
    ("BRO", "Brown & Brown, Inc."),
    ("BROS", "Dutch Bros Inc."),
    ("BRX", "Brixmor Property Group Inc."),
    ("BSM", "Black Stone Minerals, L.P."),
    ("BSX", "Boston Scientific Corporation"),
    ("BTI", "British American Tobacco Industries, p.l.c."),
    ("BTU", "Peabody Energy Corporation"),
    ("BUR", "Burford Capital Limited"),
    ("BURL", "Burlington Stores, Inc."),
    ("BV", "BrightView Holdings, Inc."),
    ("BW", "Babcock & Wilcox Enterprises, Inc."),
    ("BWA", "BorgWarner Inc."),
    ("BWIV", "Blue Water Acquisition Corp. IV Class A"),
    ("BWLP", "BW LPG Limited"),
    ("BWMX", "Betterware de Mexico, S.A.P.I. de C.V."),
    ("BWXT", "BWX Technologies, Inc."),
    ("BX", "Blackstone Inc."),
    ("BXC", "Bluelinx Holdings Inc."),
    ("BXP", "BXP, Inc."),
    ("BY", "Byline Bancorp, Inc."),
    ("BYD", "Boyd Gaming Corporation"),
    ("BZH", "Beazer Homes USA, Inc."),
    ("C", "Citigroup, Inc."),
    ("CAAP", "Corporacion America Airports SA"),
    ("CABO", "Cable One, Inc."),
    ("CACI", "CACI International, Inc. Class A"),
    ("CAG", "ConAgra Brands, Inc."),
    ("CAH", "Cardinal Health, Inc."),
    ("CAL", "Caleres, Inc."),
    ("CALX", "Calix, Inc."),
    ("CALY", "Callaway Golf Company"),
    ("CANG", "Cango Inc. Class A"),
    ("CARR", "Carrier Global Corporation"),
    ("CARS", "Cars.com Inc."),
    ("CAT", "Caterpillar, Inc."),
    ("CATO", "Cato Corporation (The) Class A"),
    ("CAVA", "CAVA Group, Inc."),
    ("CB", "Chubb Limited"),
    ("CBAN", "Colony Bankcorp, Inc."),
    ("CBL", "CBL & Associates Properties, Inc."),
    ("CBNA", "Chain Bridge Bancorp, Inc. Class A"),
    ("CBRE", "CBRE Group Inc"),
    ("CBT", "Cabot Corporation"),
    ("CBU", "Community Financial System, Inc."),
    ("CBZ", "CBIZ, Inc."),
    ("CC", "Chemours Company (The)"),
    ("CCI", "Crown Castle Inc."),
    ("CCJ", "Cameco Corporation"),
    ("CCL", "Carnival Corporation Ltd."),
    ("CCO", "Clear Channel Outdoor Holdings, Inc."),
    ("CCS", "Century Communities, Inc."),
    ("CCU", "Compania Cervecerias Unidas, S.A."),
    ("CDE", "Coeur Mining, Inc."),
    ("CDP", "COPT Defense Properties"),
    ("CDRE", "Cadre Holdings, Inc."),
    ("CE", "Celanese Corporation"),
    ("CF", "CF Industries Holdings, Inc."),
    ("CFG", "Citizens Financial Group, Inc."),
    ("CFR", "Cullen/Frost Bankers, Inc."),
    ("CGAU", "Centerra Gold Inc."),
    ("CHD", "Church & Dwight Company, Inc."),
    ("CHGG", "Chegg, Inc."),
    ("CHH", "Choice Hotels International, Inc."),
    ("CHMI", "Cherry Hill Mortgage Investment Corporation"),
    ("CHPT", "ChargePoint Holdings, Inc."),
    ("CHWY", "Chewy, Inc. Class A"),
    ("CI", "The Cigna Group"),
    ("CIA", "Citizens, Inc. Class A"),
    ("CIEN", "Ciena Corporation"),
    ("CIM", "Chimera Investment Corporation"),
    ("CINT", "CI&T Inc Class A"),
    ("CION", "CION Investment Corporation"),
    ("CLB", "Core Laboratories Inc."),
    ("CLBR", "Colombier Acquisition Corp. III Class A"),
    ("CLH", "Clean Harbors, Inc."),
    ("CLPR", "Clipper Realty Inc."),
    ("CLS", "Celestica, Inc."),
    ("CLVT", "Clarivate Plc"),
    ("CLW", "Clearwater Paper Corporation"),
    ("CLX", "Clorox Company (The)"),
    ("CM", "Canadian Imperial Bank of Commerce"),
    ("CMBT", "CMB.TECH NV"),
    ("CMC", "Commercial Metals Company"),
    ("CMDB", "Costamare Bulkers Holdings Limited"),
    ("CMG", "Chipotle Mexican Grill, Inc."),
    ("CMI", "Cummins Inc."),
    ("CMP", "Compass Minerals Intl Inc"),
    ("CMRE", "Costamare Inc."),
    ("CMS", "CMS Energy Corporation"),
    ("CNA", "CNA Financial Corporation"),
    ("CNC", "Centene Corporation"),
    ("CNH", "CNH Industrial N.V."),
    ("CNI", "Canadian National Railway Company"),
    ("CNK", "Cinemark Holdings Inc."),
    ("CNM", "Core & Main, Inc. Class A"),
    ("CNMD", "CONMED Corporation"),
    ("CNNE", "Cannae Holdings, Inc."),
    ("CNO", "CNO Financial Group, Inc."),
    ("CNP", "CenterPoint Energy, Inc."),
    ("CNQ", "Canadian Natural Resources Limited"),
    ("CNR", "Core Natural Resources, Inc."),
    ("CNS", "Cohen & Steers Inc"),
    ("CNX", "CNX Resources Corporation"),
    ("COF", "Capital One Financial Corporation"),
    ("COHR", "Coherent Corp."),
    ("COMP", "Compass, Inc. Class A"),
    ("CON", "Concentra Group Holdings Parent, Inc."),
    ("COOK", "Traeger, Inc."),
    ("COP", "ConocoPhillips"),
    ("COPL", "Copley Acquisition Corp."),
    ("COR", "Cencora, Inc."),
    ("COSO", "CoastalSouth Bancshares, Inc."),
    ("COTY", "Coty Inc. Class A"),
    ("COUR", "Coursera, Inc."),
    ("CP", "Canadian Pacific Kansas City Limited"),
    ("CPA", "Copa Holdings, S.A. Class A"),
    ("CPAY", "Corpay, Inc."),
    ("CPK", "Chesapeake Utilities Corporation"),
    ("CPNG", "Coupang, Inc. Class A"),
    ("CPRI", "Capri Holdings Limited"),
    ("CR", "Crane Company"),
    ("CRBG", "Corebridge Financial Inc."),
    ("CRC", "California Resources Corporation"),
    ("CRCL", "Circle Internet Group, Inc. Class A"),
    ("CRGY", "Crescent Energy Company Class A"),
    ("CRH", "CRH PLC"),
    ("CRI", "Carter's, Inc."),
    ("CRK", "Comstock Resources, Inc."),
    ("CRL", "Charles River Laboratories International, Inc."),
    ("CRM", "Salesforce, Inc."),
    ("CRS", "Carpenter Technology Corporation"),
    ("CSL", "Carlisle Companies Incorporated"),
    ("CSQR", "Csquare, Inc."),
    ("CSR", "Centerspace"),
    ("CSTM", "Constellium SE"),
    ("CSV", "Carriage Services, Inc."),
    ("CSW", "CSW Industrials, Inc."),
    ("CTEV", "Claritev Corporation Class A"),
    ("CTO", "CTO Realty Growth, Inc."),
    ("CTOS", "Custom Truck One Source, Inc."),
    ("CTRI", "Centuri Holdings, Inc."),
    ("CTS", "CTS Corporation"),
    ("CTVA", "Corteva, Inc."),
    ("CUBE", "CubeSmart"),
    ("CUBI", "Customers Bancorp, Inc."),
    ("CURB", "Curbline Properties Corp."),
    ("CURV", "Torrid Holdings Inc."),
    ("CUZ", "Cousins Properties Incorporated"),
    ("CVE", "Cenovus Energy Inc."),
    ("CVEO", "Civeo Corporation"),
    ("CVI", "CVR Energy Inc."),
    ("CVLG", "Covenant Logistics Group, Inc. Class A"),
    ("CVNA", "Carvana Co. Class A"),
    ("CVS", "CVS Health Corporation"),
    ("CVSA", "Covista Inc."),
    ("CVX", "Chevron Corporation"),
    ("CWEN", "Clearway Energy, Inc. Class C"),
    ("CWH", "Camping World Holdings, Inc. Class A"),
    ("CWK", "Cushman & Wakefield Ltd."),
    ("CWT", "California Water Service Group"),
    ("CXM", "Sprinklr, Inc. Class A"),
    ("CXT", "Crane NXT, Co."),
    ("CXW", "CoreCivic, Inc."),
    ("CYD", "China Yuchai International Limited"),
    ("CYH", "Community Health Systems, Inc."),
    ("D", "Dominion Energy, Inc."),
    ("DAC", "Danaos Corporation"),
    ("DAL", "Delta Air Lines, Inc."),
    ("DAN", "Dana Incorporated"),
    ("DAR", "Darling Ingredients Inc."),
    ("DB", "Deutsche Bank AG"),
    ("DBD", "Diebold Nixdorf Incorporated"),
    ("DBI", "Designer Brands Inc. Class A"),
    ("DCH", "Dauch Corporation"),
    ("DCI", "Donaldson Company, Inc."),
    ("DCO", "Ducommun Incorporated"),
    ("DCOM", "Dime Commercial Bancshares, Inc."),
    ("DD", "DuPont de Nemours, Inc."),
    ("DDD", "3D Systems Corporation"),
    ("DDS", "Dillard's, Inc."),
    ("DE", "Deere & Company"),
    ("DEA", "Easterly Government Properties, Inc."),
    ("DEC", "Diversified Energy Company"),
    ("DECK", "Deckers Outdoor Corporation"),
    ("DEI", "Douglas Emmett, Inc."),
    ("DELL", "Dell Technologies Inc. Class C"),
    ("DEO", "Diageo plc"),
    ("DFH", "Dream Finders Homes, Inc. Class A"),
    ("DFIN", "Donnelley Financial Solutions, Inc."),
    ("DG", "Dollar General Corporation"),
    ("DGAC", "Disciplined Growth Acquisition Corporation Class A"),
    ("DGX", "Quest Diagnostics Incorporated"),
    ("DHI", "D.R. Horton, Inc."),
    ("DHR", "Danaher Corporation"),
    ("DHX", "DHI Group, Inc."),
    ("DIN", "Dine Brands Global, Inc."),
    ("DINO", "HF Sinclair Corporation"),
    ("DIS", "Walt Disney Company (The)"),
    ("DK", "Delek US Holdings, Inc."),
    ("DKS", "Dick's Sporting Goods Inc"),
    ("DLB", "Dolby Laboratories"),
    ("DLX", "Deluxe Corporation"),
    ("DMC", "Del Monte Corporation"),
    ("DNA", "Ginkgo Bioworks Holdings, Inc. Class A"),
    ("DNOW", "DNOW Inc."),
    ("DOC", "Healthpeak Properties, Inc."),
    ("DOCN", "DigitalOcean Holdings, Inc."),
    ("DOCS", "Doximity, Inc. Class A"),
    ("DOLE", "Dole plc"),
    ("DOUG", "Douglas Elliman Inc."),
    ("DOV", "Dover Corporation"),
    ("DOW", "Dow Inc."),
    ("DPC", "DPC Holdings PLC"),
    ("DRI", "Darden Restaurants, Inc."),
    ("DT", "Dynatrace, Inc."),
    ("DTE", "DTE Energy Company"),
    ("DTM", "DT Midstream, Inc."),
    ("DUK", "Duke Energy Corporation"),
    ("DV", "DoubleVerify Holdings, Inc."),
    ("DVA", "DaVita Inc."),
    ("DVN", "Devon Energy Corporation"),
    ("DX", "Dynex Capital, Inc."),
    ("DXC", "DXC Technology Company"),
    ("DXYZ", "Destiny Tech100 Inc."),
    ("DY", "Dycom Industries, Inc."),
    ("E", "ENI S.p.A."),
    ("EAF", "GrafTech International Ltd."),
    ("EARN", "Ellington Credit Company"),
    ("EAT", "Brinker International, Inc."),
    ("EBF", "Ennis, Inc."),
    ("EBS", "Emergent BioSolutions Inc."),
    ("ECG", "Everus Construction Group, Inc."),
    ("ECL", "Ecolab Inc."),
    ("ECO", "Okeanis Eco Tankers Corp."),
    ("ECVT", "Ecovyst Inc."),
    ("ED", "Consolidated Edison, Inc."),
    ("EE", "Excelerate Energy, Inc. Class A"),
    ("EFC", "Ellington Financial Inc."),
    ("EFOR", "Everforth, Inc."),
    ("EFX", "Equifax, Inc."),
    ("EFXT", "Enerflex Ltd"),
    ("EG", "Everest Group, Ltd."),
    ("EGO", "Eldorado Gold Corporation"),
    ("EGP", "EastGroup Properties, Inc."),
    ("EGY", "VAALCO Energy, Inc."),
    ("EHC", "Encompass Health Corporation"),
    ("EIG", "Employers Holdings Inc"),
    ("EIX", "Edison International"),
    ("EL", "Estee Lauder Companies, Inc. (The)"),
    ("ELAN", "Elanco Animal Health Incorporated"),
    ("ELF", "e.l.f. Beauty, Inc."),
    ("ELME", "Elme Communities"),
    ("ELS", "Equity Lifestyle Properties, Inc."),
    ("ELV", "Elevance Health, Inc."),
]

async def init():
    x = Session()
    for symbol, name in nyse_stocks:
        new_stock = Stock(symbol=symbol, name=name, initial_listing=100.00)
        x.add(new_stock)

    await x.commit()

if __name__ == "__main__":
    asyncio.run(init())